meta_product_name: "Roam Master"
meta_title: "Roam Master - Your Ultimate Trip Planner"
meta_description: "Set your budget, organize activities, and find the perfect accommodations with ease.
Say goodbye to stress and hello to a seamless travel experience"
meta_image: "cover.png" # should exist in `app/assets/images/`
